/***************************************************************************************\
 * PROJECT NAME          : IPNC          								               *        
 * MODULE NAME           : Macro Defines for menu display and settings page            *
 *                                                                                     *
 * Copyright (c) 2008 - GoDB Tech Private Limited. All rights reserved.                *
 * THIS SOURCE CODE IS PROVIDED AS-IS WITHOUT ANY EXPRESSED OR IMPLIED                 *
 * WARRANTY OF ANY KIND INCLUDING THOSE OF MERCHANTABILITY, NONINFRINGEMENT            *
 * OF THIRD-PARTY INTELLECTUAL PROPERTY, OR FITNESS FOR A PARTICULAR PURPOSE.          *
 * NEITHER GoDB NOR ITS SUPPLIERS SHALL BE LIABLE FOR ANY DAMAGES WHATSOEVER           *
 * (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF BUSINESS PROFITS,               *
 * BUSINESS INTERRUPTION, LOSS OF BUSINESS INFORMATION, OR OTHER LOSS)                 *
 * ARISING OUT OF THE USE OF OR INABILITY TO USE THE SOFTWARE, EVEN IF GoDB            *
 * HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.                                *
 *                                                                                     *
 * DO-NOT COPY,DISTRIBUTE,EMAIL,STORE THIS CODE WITHOUT PRIOR WRITTEN                  *
 * PERMISSION FROM GoDBTech.                                                           *
\***************************************************************************************/

#define PC_VERSION 1	' Standalone version (default)
#define WEB_VERSION 2	' Web version

#define MAX_VALUES              300

#define MAXMAINMENU 			5
#define MAXSUBMENU				9
#define LEFTMENUCTRLS 			25

#define OPERATOR 				1
#define VIEWER 					2
#define ADMIN 					0
#define SUPERADMIN 				3

#define HEADER_HEIGHT           60
#define CONTROL_HEIGHT          22
#define BUTTON_WIDTH            74
#define BUTTON_GAP              6

#define TRUE                    1
#define FALSE                   0

#define DISPLAY_REGION_X        242
#define DISPLAY_REGION_Y        10
#define DISPLAY_REGION_BG       4358
#define DISPLAY_REGION_H        534
#define BORDER_GAP              10
#define TRANS_COL               61458

#define BG_IMG_W                1038

#define DISABLE_COLOR           31631

#define DESIGN_XVAL 			1024
#define DESIGN_YVAL 			650

#define UNSELECTED_TXT_COLOR      17004
#define UNSELECTED_BRD_COLOR	  14826
#define UNSELECTED_BG_COLOR	      14826

#define SUPRESSUI			0


SETOSVAR("*FLUSHEVENTS", "")




