LabelName$(0) = "gdosdExplorer" : XPos(0) = 248: YPos(0) = 115: Wdh(0) = 264: Height(0) = 128
LabelName$(1) = "cmdBack" : XPos(1) = 248: YPos(1) = 558: Wdh(1) = 100: Height(1) = 20
LabelName$(2) = "cmdFormat" : XPos(2) = 248: YPos(2) = 81: Wdh(2) = 100: Height(2) = 20
LabelName$(3) = "cmdMount" : XPos(3) = 366: YPos(3) = 81: Wdh(3) = 100: Height(3) = 20
LabelName$(4) = "lblupdate" : XPos(4) = 458: YPos(4) = 283: Wdh(4) = 162: Height(4) = 30
